apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-operator
  namespace: cluo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: container-linux-update-operator
    spec:
      serviceAccount: update-operator
      containers:
      - name: update-operator
        image: quay.io/coreos/container-linux-update-operator:v0.7.0
        command:
        - "/bin/update-operator"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
