apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: update-operator
  namespace: cluo
rules:
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [create, get, update, list, watch]
  - apiGroups: [""]
    resources: [events]
    verbs: [create, watch]
