#
# Copyright 2019, Ridecell, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ridecell-operator-webui
  namespace: ridecell-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ridecell-operator-webui
rules:
- apiGroups: [""]
  resources: [pods]
  verbs: ["get", "list"]
- apiGroups: [apps]
  resources: [deployments]
  verbs: ["get", "list"]
- apiGroups: [summon.ridecell.io]
  resources: ["*"]
  verbs: ["get", "list"]
- apiGroups: [db.ridecell.io]
  resources: ["*"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ridecell-operator-webui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ridecell-operator-webui
subjects:
- name: ridecell-operator-webui
  namespace: ridecell-operator
  kind: ServiceAccount
---
apiVersion: v1
kind: Service
metadata:
  name: ridecell-operator-webui
  namespace: ridecell-operator
  labels:
    app: ridecell-operator
spec:
  ports:
    - port: 3000
  selector:
    app: ridecell-operator-webui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ridecell-operator-webui
  namespace: ridecell-operator
spec:
  selector:
    matchLabels:
      app: ridecell-operator-webui
  template:
    metadata:
      labels:
        app: ridecell-operator-webui
    spec:
      serviceAccountName: ridecell-operator-webui
      imagePullSecrets:
      - name: pull-secret
      containers:
      - name: default
        image: us.gcr.io/ridecell-1/ridecell-operator:2029-00e3d8a-master
        command: [/webui]
        ports:
          - containerPort: 3000
        resources:
          limits:
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 100Mi
        envFrom:
        - secretRef:
            name: ridecell-operator-webui
      terminationGracePeriodSeconds: 10
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ridecell-operator-webui
  namespace: ridecell-operator
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: hostname
    http:
      paths:
      - path: /
        backend:
          serviceName: ridecell-operator-webui
          servicePort: 3000
  tls:
  - secretName: ridecell-operator-webui-tls
    hosts:
    - hostname
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: ridecell-operator-webui
#   namespace: ridecell-operator
# stringData:
#   HOST:
#   GITHUB_KEY:
#   GITHUB_SECRET:
